version: "2"
services:
  redis:
    restart: always
    image: sameersbn/redis:4.0.9-1
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z
  gitlab:
    restart: always
    image: sameersbn/gitlab:10.7.1
    depends_on:
      - redis
    ports:
      - "81:80"
      - "443:443"
      - "22:22"
      - "25:25"
      - "587:587"
      - "995:995"
      - "993:993"
      - "110:110"
    volumes:
      - /srv/docker/gitlab/gitlab:/home/git/data
    environment:
      - DEBUG=true
      - DB_ADAPTER=
      - DB_HOST=
      - DB_NAME=
      - DB_USER=
      - DB_PASS=

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - UNICORN_TIMEOUT=900
      - UNICORN_WORKERS=4

      - GITLAB_HTTPS=true
      - SSL_SELF_SIGNED=true

      - GITLAB_HOST=
      - GITLAB_PORT=443
      - GITLAB_SSH_PORT=22
      - GITLAB_RELATIVE_URL_ROOT=
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

     - GITLAB_PAGES_ENABLED=true
      - GITLAB_PAGES_DOMAIN=
      - GITLAB_PAGES_HTTPS=
      - SSL_CERTIFICATE_PATH=
      - SSL_KEY_PATH=
      - SSL_DHPARAM_PATH=
      - SSL_VERIFY_CLIENT=on
      - NGINX_HSTS_MAXAGE=2592000
      - NGINX_HSTS_ENABLED=true
  
      - GITLAB_EMAIL=
      - GITLAB_EMAIL_REPLY_TO=
      - SMTP_ENABLED=true
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_DOMAIN=
      - SMTP_TLS=false
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login
      - SMTP_OPENSSL_VERIFY_MODE=none

      - GITLAB_TIMEZONE=Asia/Bangkok

      - GITLAB_ROOT_PASSWORD=
      - GITLAB_ROOT_EMAIL=

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=
      - GITLAB_EMAIL_REPLY_TO=
      - GITLAB_INCOMING_EMAIL_ADDRESS=

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

      - OAUTH_ENABLED=
      - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
      - OAUTH_ALLOW_SSO=
      - OAUTH_BLOCK_AUTO_CREATED_USERS=
      - OAUTH_AUTO_LINK_LDAP_USER=
      - OAUTH_AUTO_LINK_SAML_USER=
      - OAUTH_EXTERNAL_PROVIDERS=

      - OAUTH_CAS3_LABEL=
      - OAUTH_CAS3_SERVER=
      - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=
      - OAUTH_CAS3_LOGIN_URL=
      - OAUTH_CAS3_VALIDATE_URL=
      - OAUTH_CAS3_LOGOUT_URL=

      - OAUTH_GOOGLE_API_KEY=
      - OAUTH_GOOGLE_APP_SECRET=
      - OAUTH_GOOGLE_RESTRICT_DOMAIN=
      - RACK_ATTACK_ENABLED=
      
      - AWS_BACKUPS=
      - AWS_BACKUP_REGION=
      - AWS_BACKUP_BUCKET=
      - AWS_BACKUP_ACCESS_KEY_ID=
      - AWS_BACKUP_SECRET_ACCESS_KEY=
