version: "3.0"
services:
  mysqlwp:
    container_name: mysqlwp
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${PASSWORD}
    restart: always
    #Mount database
    volumes:
      - '${MYSQL_DATA_DIR}:/var/lib/mysql'
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    environment:
      - WORDPRESS_DB_NAME=${DATABASE}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${PASSWORD}
    ports:
      - '8080:80'
    links:
      - 'mysqlwp:mysql'
    depends_on:
      - 'mysqlwp'
    #Mount source code
    volumes:
      - '${SOURCE_CODE_DIR}:/var/www/html'
    restart: always
  phpMyAdmin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin
    links:
      - 'mysqlwp:mysql'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysqlwp
    depends_on:
      - 'mysqlwp'
    ports:
      - '8888:80'
    restart: always
